/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
// System headers
#include <stdio.h>

// Device driver headers
#include "systick.h"
#include "i2c.h"
#include "gpio.h"
#include "display.h"
#include "touchpad.h"

// App headers
#include "alarm.h"
#include "game.h"
#include "calc.h"
#include "spi.h"
#include "enviro.h"

int main(void)
{
    // Initialize apps
    Init_Alarm();
    Init_Game();
    Init_Calc();

    // initiate environment
    Init_Enviro();

    // initiate motor
    Init_Motor();

    // Enable system services
    StartSysTick();

    while (1) {
        // Run apps
        Task_Alarm();
        Task_Game();
        Task_Calc();

        // Run environment
        Task_Enviro();

        //motor
        Task_Motor();

        // Housekeeping
        UpdateIOExpanders();
        UpdateDisplay();
        ScanTouchpad();
        ServiceI2CRequests();
        ServiceSPIRequests();
        WaitForSysTick();
    }
}
